var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":94,"id":719,"methods":[{"el":45,"sc":5,"sl":36},{"el":57,"sc":5,"sl":47},{"el":69,"sc":5,"sl":59},{"el":81,"sc":5,"sl":71},{"el":93,"sc":5,"sl":83}],"name":"ValidateProjectTypeTest","sl":34}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_12":{"methods":[{"sl":83}],"name":"validateExceptionOnParentPomWithModules","pass":true,"statements":[{"sl":87},{"sl":88},{"sl":89},{"sl":92}]},"test_2":{"methods":[{"sl":71}],"name":"validateAspectPom","pass":true,"statements":[{"sl":75},{"sl":76},{"sl":77},{"sl":80}]},"test_25":{"methods":[{"sl":47}],"name":"validateCorrectPom","pass":true,"statements":[{"sl":51},{"sl":52},{"sl":53},{"sl":56}]},"test_5":{"methods":[{"sl":83}],"name":"validateExceptionOnParentPomWithModules","pass":true,"statements":[{"sl":87},{"sl":88},{"sl":89},{"sl":92}]},"test_52":{"methods":[{"sl":36}],"name":"validateCacheability","pass":true,"statements":[{"sl":40},{"sl":43},{"sl":44}]},"test_58":{"methods":[{"sl":59}],"name":"validateTestProjectTypePom","pass":true,"statements":[{"sl":63},{"sl":64},{"sl":65},{"sl":68}]},"test_59":{"methods":[{"sl":71}],"name":"validateAspectPom","pass":true,"statements":[{"sl":75},{"sl":76},{"sl":77},{"sl":80}]},"test_63":{"methods":[{"sl":47}],"name":"validateCorrectPom","pass":true,"statements":[{"sl":51},{"sl":52},{"sl":53},{"sl":56}]},"test_64":{"methods":[{"sl":59}],"name":"validateTestProjectTypePom","pass":true,"statements":[{"sl":63},{"sl":64},{"sl":65},{"sl":68}]},"test_8":{"methods":[{"sl":36}],"name":"validateCacheability","pass":true,"statements":[{"sl":40},{"sl":43},{"sl":44}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [8, 52], [], [], [], [8, 52], [], [], [8, 52], [8, 52], [], [], [63, 25], [], [], [], [63, 25], [63, 25], [63, 25], [], [], [63, 25], [], [], [58, 64], [], [], [], [58, 64], [58, 64], [58, 64], [], [], [58, 64], [], [], [2, 59], [], [], [], [2, 59], [2, 59], [2, 59], [], [], [2, 59], [], [], [12, 5], [], [], [], [12, 5], [12, 5], [12, 5], [], [], [12, 5], [], []]
